name: build contents
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: natsukium
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: check
        run: nix flake check
